[h2o website](https://docs.h2o.ai/h2o/latest-stable/h2o-docs/automl.html)

Performance :https://docs.h2o.ai/h2o/latest-stable/h2o-docs/performance-and-prediction.html

tutorial :https://www.youtube.com/watch?v=91QljBnvM7s&ab_channel=AIEngineering

another_code:https://colab.research.google.com/github/srivatsan88/YouTubeLI/blob/master/H2O_AutoML.ipynb#scrollTo=BiTtGL6IcA8J

https://towardsdatascience.com/automated-machine-learning-with-h2o-258a2f3a203f

https://h2oai.atlassian.net/browse/PUBDEV-7936?filter=21603

In [2]:
pip install requests

Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (2.23.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests) (2021.10.8)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests) (1.24.3)

In [3]:
pip install tabulate

Requirement already satisfied: tabulate in /usr/local/lib/python3.7/dist-packages (0.8.9)

In [4]:
pip install "colorama>=0.3.8"

Collecting colorama>=0.3.8
  Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Installing collected packages: colorama
Successfully installed colorama-0.4.4

In [5]:
pip install future

Requirement already satisfied: future in /usr/local/lib/python3.7/dist-packages (0.16.0)

In [6]:
pip install h2o

Collecting h2o
  Downloading h2o-3.36.0.3.tar.gz (176.2 MB)
     |████████████████████████████████| 176.2 MB 74 kB/s
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from h2o) (2.23.0)
Requirement already satisfied: tabulate in /usr/local/lib/python3.7/dist-packages (from h2o) (0.8.9)
Requirement already satisfied: future in /usr/local/lib/python3.7/dist-packages (from h2o) (0.16.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->h2o) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->h2o) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->h2o) (2021.10.8)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->h2o) (3.0.4)
Building wheels for collected packages: h2o
  Building wheel for h2o (setup.py) ... done
  Created wheel for h2o: filename=h2o-3.36.0.3-py2.py3-none-any.whl size=176244303 sha256=5775d1a483de0e05a9197cabfd14cf2cdc609d65c121f394194fc9355e39e6ae
  Stored in directory: /root/.cache/pip/wheels/b5/71/a5/02087a05e5644158183e1c58eeae3f9356a4d1e80659fb2dfb
Successfully built h2o
Installing collected packages: h2o
Successfully installed h2o-3.36.0.3

# our code

In [7]:
import h2o
from h2o.automl import H2OAutoML
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321 ..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "11.0.14" 2022-01-18; OpenJDK Runtime Environment (build 11.0.14+9-Ubuntu-0ubuntu2.18.04); OpenJDK 64-Bit Server VM (build 11.0.14+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)
  Starting server from /usr/local/lib/python3.7/dist-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmpwk2eawhp
  JVM stdout: /tmp/tmpwk2eawhp/h2o_unknownUser_started_from_python.out
  JVM stderr: /tmp/tmpwk2eawhp/h2o_unknownUser_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  ----------------------------------
H2O_cluster_uptime:         02 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.36.0.3
H2O_cluster_version_age:    1 month and 4 days
H2O_cluster_name:           H2O_from_python_unknownUser_n2802y
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    3.172 Gb
H2O_cluster_total_cores:    2
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
Python_version:             3.7.12 final
--------------------------  ----------------------------------

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [9]:
# Import a sample binary outcome train/test set into H2O
prostate = h2o.import_file("/content/drive/MyDrive/breast cancer datasets/DB1.csv")
prostate.head()

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

X.0,X.2,X.3,X.4,X.5,X.6,X.7,X.8,X.9,X.10,X.11,X.12,X.13,X.14,X.15,X.16,X.17,X.18,X.19,X.20,X.21,X.22,X.23,X.24,X.25,X.26,X.27,X.28,X.29,X.30,X.31,class
842302,17.99,10.38,122.8,1001,0.1184,0.2776,0.3001,0.1471,0.2419,0.07871,1.095,0.9053,8.589,153.4,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.6,2019,0.1622,0.6656,0.7119,0.2654,0.4601,0.1189,M
842517,20.57,17.77,132.9,1326,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.0186,0.0134,0.01389,0.003532,24.99,23.41,158.8,1956,0.1238,0.1866,0.2416,0.186,0.275,0.08902,M
8.43009e+07,19.69,21.25,130,1203,0.1096,0.1599,0.1974,0.1279,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.00615,0.04006,0.03832,0.02058,0.0225,0.004571,23.57,25.53,152.5,1709,0.1444,0.4245,0.4504,0.243,0.3613,0.08758,M
8.43483e+07,11.42,20.38,77.58,386.1,0.1425,0.2839,0.2414,0.1052,0.2597,0.09744,0.4956,1.156,3.445,27.23,0.00911,0.07458,0.05661,0.01867,0.05963,0.009208,14.91,26.5,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.173,M
8.43584e+07,20.29,14.34,135.1,1297,0.1003,0.1328,0.198,0.1043,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.01149,0.02461,0.05688,0.01885,0.01756,0.005115,22.54,16.67,152.2,1575,0.1374,0.205,0.4,0.1625,0.2364,0.07678,M
843786,12.45,15.7,82.57,477.1,0.1278,0.17,0.1578,0.08089,0.2087,0.07613,0.3345,0.8902,2.217,27.19,0.00751,0.03345,0.03672,0.01137,0.02165,0.005082,15.47,23.75,103.4,741.6,0.1791,0.5249,0.5355,0.1741,0.3985,0.1244,M
844359,18.25,19.98,119.6,1040,0.09463,0.109,0.1127,0.074,0.1794,0.05742,0.4467,0.7732,3.18,53.91,0.004314,0.01382,0.02254,0.01039,0.01369,0.002179,22.88,27.66,153.2,1606,0.1442,0.2576,0.3784,0.1932,0.3063,0.08368,M
8.44582e+07,13.71,20.83,90.2,577.9,0.1189,0.1645,0.09366,0.05985,0.2196,0.07451,0.5835,1.377,3.856,50.96,0.008805,0.03029,0.02488,0.01448,0.01486,0.005412,17.06,28.14,110.6,897,0.1654,0.3682,0.2678,0.1556,0.3196,0.1151,M
844981,13,21.82,87.5,519.8,0.1273,0.1932,0.1859,0.09353,0.235,0.07389,0.3063,1.002,2.406,24.32,0.005731,0.03502,0.03553,0.01226,0.02143,0.003749,15.49,30.73,106.2,739.3,0.1703,0.5401,0.539,0.206,0.4378,0.1072,M
8.4501e+07,12.46,24.04,83.97,475.9,0.1186,0.2396,0.2273,0.08543,0.203,0.08243,0.2976,1.599,2.039,23.94,0.007149,0.07217,0.07743,0.01432,0.01789,0.01008,15.09,40.68,97.65,711.4,0.1853,1.058,1.105,0.221,0.4366,0.2075,M

In [10]:
# split into train and testing sets
train, test = prostate.split_frame(ratios = [0.8], seed = 123)
x = train.columns
y = "class"
x.remove(y)
# For binary classification, response should be a factor
train[y] = train[y].asfactor()
test[y] = test[y].asfactor()

# Run AutoML for 10 base models (limited to 1 hour max runtime by default)
aml = H2OAutoML(max_models=20, seed=1)
aml.train(x=x, y=y, training_frame=train)

# View the AutoML Leaderboard
lb = aml.leaderboard
lb.head(rows=lb.nrows)

AutoML progress: |███████████████████████████████████████████████████████████████| (done) 100%

model_id,auc,logloss,aucpr,mean_per_class_error,rmse,mse
GLM_1_AutoML_1_20220321_152754,0.992063,0.0935164,0.991318,0.0272923,0.153972,0.0237073
StackedEnsemble_BestOfFamily_6_AutoML_1_20220321_152754,0.99181,0.0913039,0.99139,0.0237462,0.151368,0.0229124
StackedEnsemble_AllModels_1_AutoML_1_20220321_152754,0.991789,0.0915273,0.99136,0.0249493,0.152181,0.023159
StackedEnsemble_BestOfFamily_3_AutoML_1_20220321_152754,0.991578,0.0906502,0.991371,0.0219732,0.14912,0.0222368
StackedEnsemble_AllModels_5_AutoML_1_20220321_152754,0.991536,0.0940439,0.990993,0.0237462,0.153788,0.0236507
StackedEnsemble_BestOfFamily_2_AutoML_1_20220321_152754,0.991367,0.091241,0.991062,0.0267224,0.150007,0.022502
StackedEnsemble_AllModels_2_AutoML_1_20220321_152754,0.991008,0.0943953,0.990533,0.0290653,0.155784,0.0242686
GBM_1_AutoML_1_20220321_152754,0.990417,0.113345,0.987532,0.039767,0.178965,0.0320286
StackedEnsemble_BestOfFamily_1_AutoML_1_20220321_152754,0.99029,0.0954996,0.990356,0.0219732,0.14963,0.0223891
GBM_2_AutoML_1_20220321_152754,0.989974,0.128308,0.986027,0.0450861,0.189692,0.0359832
XGBoost_2_AutoML_1_20220321_152754,0.989066,0.120547,0.986687,0.0469225,0.180176,0.0324632
GBM_3_AutoML_1_20220321_152754,0.988961,0.127858,0.985213,0.0439463,0.186851,0.0349133
XGBoost_3_AutoML_1_20220321_152754,0.987378,0.122638,0.984847,0.0474291,0.187984,0.0353378
GBM_4_AutoML_1_20220321_152754,0.987335,0.134541,0.983704,0.0511018,0.19227,0.0369677
XRT_1_AutoML_1_20220321_152754,0.984306,0.265082,0.982189,0.0462893,0.192634,0.0371079
StackedEnsemble_AllModels_4_AutoML_1_20220321_152754,0.983905,0.124063,0.984661,0.0368541,0.170692,0.0291356
DRF_1_AutoML_1_20220321_152754,0.981657,0.279984,0.97895,0.0540147,0.205896,0.0423933
StackedEnsemble_AllModels_3_AutoML_1_20220321_152754,0.980739,0.117426,0.983354,0.031535,0.160256,0.025682
StackedEnsemble_BestOfFamily_5_AutoML_1_20220321_152754,0.978407,0.1065,0.983168,0.031535,0.157014,0.0246535
XGBoost_1_AutoML_1_20220321_152754,0.977299,0.191867,0.968078,0.0658561,0.228287,0.0521151
StackedEnsemble_BestOfFamily_4_AutoML_1_20220321_152754,0.976106,0.125745,0.981545,0.0296986,0.159672,0.025495

In [11]:
preds = aml.leader.predict(test)
print(preds)

glm prediction progress: |███████████████████████████████████████████████████████| (done) 100%

predict,B,M
M,0.0091603,0.99084
M,0.00149556,0.998504
M,0.0656921,0.934308
M,0.000701821,0.999298
B,0.999131,0.000868999
M,0.148081,0.851919
M,0.0764635,0.923536
B,0.984598,0.0154015
B,0.998209,0.00179105
B,0.999874,0.000126392

In [12]:
# Get the best model using the metric
m = aml.leader
# this is equivalent to
m = aml.get_best_model()
print(m)

Model Details
=============
H2OGeneralizedLinearEstimator :  Generalized Linear Modeling
Model Key:  GLM_1_AutoML_1_20220321_152754


GLM Model: summary

,,family,link,regularization,lambda_search,number_of_predictors_total,number_of_active_predictors,number_of_iterations,training_frame
0,,binomial,logit,Ridge ( lambda = 0.005248 ),"nlambda = 30, lambda.max = 38.202, lambda.min = 0.005248, lambda.1...",31,31,58,AutoML_1_20220321_152754_training_py_5_sid_b915

ModelMetricsBinomialGLM: glm
** Reported on train data. **

MSE: 0.015944831464351737
RMSE: 0.12627284531660693
LogLoss: 0.06540044841416845
Null degrees of freedom: 449
Residual degrees of freedom: 418
Null deviance: 594.6353393993376
Residual deviance: 58.86040357275161
AIC: 122.86040357275161
AUC: 0.9971715636609254
AUCPR: 0.9963210459856495
Gini: 0.9943431273218508

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.41470241461022955:

              B      M   Error          Rate
0      B  280.0    2.0  0.0071   (2.0/282.0)
1      M    4.0  164.0  0.0238   (4.0/168.0)
2  Total  284.0  166.0  0.0133   (6.0/450.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric     threshold       value    idx
0                        max f1  4.147024e-01    0.982036  123.0
1                        max f2  4.147024e-01    0.978520  123.0
2                  max f0point5  5.725890e-01    0.992647  119.0
3                  max accuracy  5.725890e-01    0.986667  119.0
4                 max precision  9.999998e-01    1.000000    0.0
5                    max recall  2.059730e-02    1.000000  206.0
6               max specificity  9.999998e-01    1.000000    0.0
7              max absolute_mcc  5.725890e-01    0.971698  119.0
8    max min_per_class_accuracy  4.147024e-01    0.976190  123.0
9   max mean_per_class_accuracy  4.147024e-01    0.984549  123.0
10                      max tns  9.999998e-01  282.000000    0.0
11                      max fns  9.999998e-01  143.000000    0.0
12                      max fps  7.723554e-08  282.000000  399.0
13                      max tps  2.059730e-02  168.000000  206.0
14                      max tnr  9.999998e-01    1.000000    0.0
15                      max fnr  9.999998e-01    0.851190    0.0
16                      max fpr  7.723554e-08    1.000000  399.0
17                      max tpr  2.059730e-02    1.000000  206.0

Gains/Lift Table: Avg response rate: 37.33 %, avg score: 37.33 %

,group,cumulative_data_fraction,lower_threshold,lift,cumulative_lift,response_rate,score,cumulative_response_rate,cumulative_score,capture_rate,cumulative_capture_rate,gain,cumulative_gain,kolmogorov_smirnov
0,1,0.011111,1.000000e+00,2.678571,2.678571,1.000000,1.000000,1.000000,1.000000,0.029762,0.029762,167.857143,167.857143,0.029762
1,2,0.020000,1.000000e+00,2.678571,2.678571,1.000000,1.000000,1.000000,1.000000,0.023810,0.053571,167.857143,167.857143,0.053571
2,3,0.031111,9.999999e-01,2.678571,2.678571,1.000000,1.000000,1.000000,1.000000,0.029762,0.083333,167.857143,167.857143,0.083333
3,4,0.040000,9.999997e-01,2.678571,2.678571,1.000000,1.000000,1.000000,1.000000,0.023810,0.107143,167.857143,167.857143,0.107143
4,5,0.051111,9.999995e-01,2.678571,2.678571,1.000000,1.000000,1.000000,1.000000,0.029762,0.136905,167.857143,167.857143,0.136905
5,6,0.100000,9.999797e-01,2.678571,2.678571,1.000000,0.999994,1.000000,0.999997,0.130952,0.267857,167.857143,167.857143,0.267857
6,7,0.151111,9.998076e-01,2.678571,2.678571,1.000000,0.999928,1.000000,0.999974,0.136905,0.404762,167.857143,167.857143,0.404762
7,8,0.200000,9.976811e-01,2.678571,2.678571,1.000000,0.999240,1.000000,0.999794,0.130952,0.535714,167.857143,167.857143,0.535714
8,9,0.300000,9.424508e-01,2.678571,2.678571,1.000000,0.984191,1.000000,0.994593,0.267857,0.803571,167.857143,167.857143,0.803571
9,10,0.400000,1.924779e-01,1.785714,2.455357,0.666667,0.615740,0.916667,0.899880,0.178571,0.982143,78.571429,145.535714,0.928951
10,11,0.500000,4.522586e-02,0.119048,1.988095,0.044444,0.099026,0.742222,0.739709,0.011905,0.994048,-88.095238,98.809524,0.788374
11,12,0.600000,1.242193e-02,0.059524,1.666667,0.022222,0.023990,0.622222,0.620422,0.005952,1.000000,-94.047619,66.666667,0.638298
12,13,0.700000,4.203537e-03,0.000000,1.428571,0.000000,0.007475,0.533333,0.532858,0.000000,1.000000,-100.000000,42.857143,0.478723
13,14,0.800000,1.394253e-03,0.000000,1.250000,0.000000,0.002554,0.466667,0.466570,0.000000,1.000000,-100.000000,25.000000,0.319149
14,15,0.900000,2.528208e-04,0.000000,1.111111,0.000000,0.000658,0.414815,0.414802,0.000000,1.000000,-100.000000,11.111111,0.159574
15,16,1.000000,7.723554e-08,0.000000,1.000000,0.000000,0.000111,0.373333,0.373333,0.000000,1.000000,-100.000000,0.000000,0.000000

ModelMetricsBinomialGLM: glm
** Reported on cross-validation data. **

MSE: 0.023707314829084666
RMSE: 0.15397179881096623
LogLoss: 0.09351643208791445
Null degrees of freedom: 449
Residual degrees of freedom: 418
Null deviance: 599.9430074296647
Residual deviance: 84.16478887912304
AIC: 148.16478887912302
AUC: 0.9920634920634921
AUCPR: 0.9913180668482248
Gini: 0.9841269841269842

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.33382471281552806:

              B      M   Error           Rate
0      B  275.0    7.0  0.0248    (7.0/282.0)
1      M    5.0  163.0  0.0298    (5.0/168.0)
2  Total  280.0  170.0  0.0267   (12.0/450.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric     threshold       value    idx
0                        max f1  3.338247e-01    0.964497  135.0
1                        max f2  3.338247e-01    0.967933  135.0
2                  max f0point5  5.875118e-01    0.984848  121.0
3                  max accuracy  5.875118e-01    0.973333  121.0
4                 max precision  9.999999e-01    1.000000    0.0
5                    max recall  1.492819e-03    1.000000  322.0
6               max specificity  9.999999e-01    1.000000    0.0
7              max absolute_mcc  5.875118e-01    0.943753  121.0
8    max min_per_class_accuracy  3.338247e-01    0.970238  135.0
9   max mean_per_class_accuracy  3.338247e-01    0.972708  135.0
10                      max tns  9.999999e-01  282.000000    0.0
11                      max fns  9.999999e-01  152.000000    0.0
12                      max fps  3.708307e-07  282.000000  399.0
13                      max tps  1.492819e-03  168.000000  322.0
14                      max tnr  9.999999e-01    1.000000    0.0
15                      max fnr  9.999999e-01    0.904762    0.0
16                      max fpr  3.708307e-07    1.000000  399.0
17                      max tpr  1.492819e-03    1.000000  322.0

Gains/Lift Table: Avg response rate: 37.33 %, avg score: 37.09 %

,group,cumulative_data_fraction,lower_threshold,lift,cumulative_lift,response_rate,score,cumulative_response_rate,cumulative_score,capture_rate,cumulative_capture_rate,gain,cumulative_gain,kolmogorov_smirnov
0,1,0.013333,1.000000e+00,2.678571,2.678571,1.000000,1.000000,1.000000,1.000000,0.035714,0.035714,167.857143,167.857143,0.035714
1,2,0.020000,1.000000e+00,2.678571,2.678571,1.000000,1.000000,1.000000,1.000000,0.017857,0.053571,167.857143,167.857143,0.053571
2,3,0.031111,9.999998e-01,2.678571,2.678571,1.000000,1.000000,1.000000,1.000000,0.029762,0.083333,167.857143,167.857143,0.083333
3,4,0.040000,9.999992e-01,2.678571,2.678571,1.000000,1.000000,1.000000,1.000000,0.023810,0.107143,167.857143,167.857143,0.107143
4,5,0.051111,9.999988e-01,2.678571,2.678571,1.000000,0.999999,1.000000,1.000000,0.029762,0.136905,167.857143,167.857143,0.136905
5,6,0.100000,9.999736e-01,2.678571,2.678571,1.000000,0.999990,1.000000,0.999995,0.130952,0.267857,167.857143,167.857143,0.267857
6,7,0.151111,9.996960e-01,2.678571,2.678571,1.000000,0.999887,1.000000,0.999958,0.136905,0.404762,167.857143,167.857143,0.404762
7,8,0.200000,9.967022e-01,2.678571,2.678571,1.000000,0.998872,1.000000,0.999693,0.130952,0.535714,167.857143,167.857143,0.535714
8,9,0.300000,9.307274e-01,2.678571,2.678571,1.000000,0.978239,1.000000,0.992542,0.267857,0.803571,167.857143,167.857143,0.803571
9,10,0.400000,2.204994e-01,1.666667,2.425595,0.622222,0.583056,0.905556,0.890170,0.166667,0.970238,66.666667,142.559524,0.909954
10,11,0.500000,5.282988e-02,0.178571,1.976190,0.066667,0.108407,0.737778,0.733818,0.017857,0.988095,-82.142857,97.619048,0.778875
11,12,0.600000,1.520830e-02,0.059524,1.656746,0.022222,0.027144,0.618519,0.616039,0.005952,0.994048,-94.047619,65.674603,0.628799
12,13,0.700000,4.747271e-03,0.000000,1.420068,0.000000,0.008316,0.530159,0.529221,0.000000,0.994048,-100.000000,42.006803,0.469225
13,14,0.800000,1.483150e-03,0.059524,1.250000,0.022222,0.003056,0.466667,0.463451,0.005952,1.000000,-94.047619,25.000000,0.319149
14,15,0.900000,3.548980e-04,0.000000,1.111111,0.000000,0.000762,0.414815,0.412041,0.000000,1.000000,-100.000000,11.111111,0.159574
15,16,1.000000,3.700000e-07,0.000000,1.000000,0.000000,0.000134,0.373333,0.370850,0.000000,1.000000,-100.000000,0.000000,0.000000

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,accuracy,0.977778,0.017568,1.000000,0.977778,0.966667,0.955556,0.988889
1,auc,0.991709,0.011953,1.000000,0.997942,0.995445,0.970679,0.994479
2,err,0.022222,0.017568,0.000000,0.022222,0.033333,0.044444,0.011111
3,err_count,2.000000,1.581139,0.000000,2.000000,3.000000,4.000000,1.000000
4,f0point5,0.978179,0.017056,1.000000,0.957447,0.967742,0.975610,0.990099
5,f1,0.969952,0.021628,1.000000,0.972973,0.960000,0.941176,0.975610
6,f2,0.962404,0.035584,1.000000,0.989011,0.952381,0.909091,0.961538
7,lift_top_group,2.817314,0.822681,2.432432,2.500000,2.368421,2.500000,4.285714
8,logloss,0.089257,0.056666,0.033640,0.077761,0.089971,0.183341,0.061572
9,max_per_class_error,0.049680,0.040046,0.000000,0.037037,0.052632,0.111111,0.047619
10,mcc,0.953087,0.034621,1.000000,0.955134,0.931681,0.909718,0.968904
11,mean_per_class_accuracy,0.973237,0.020652,1.000000,0.981482,0.964069,0.944444,0.976190
12,mean_per_class_error,0.026763,0.020652,0.000000,0.018519,0.035931,0.055556,0.023810
13,mse,0.023628,0.015040,0.005620,0.022521,0.027841,0.046089,0.016071
14,null_deviance,119.988600,5.650968,122.759590,121.567660,124.005860,121.567660,110.042240
15,pr_auc,0.989826,0.011474,1.000000,0.996996,0.994184,0.971319,0.986632
16,precision,0.984068,0.023619,1.000000,0.947368,0.972973,1.000000,1.000000
17,r2,0.897389,0.060567,0.976785,0.906164,0.885873,0.807964,0.910160
18,recall,0.957728,0.045958,1.000000,1.000000,0.947368,0.888889,0.952381
19,residual_deviance,16.066265,10.199904,6.055276,13.997009,16.194714,33.001434,11.082891

See the whole table with table.as_data_frame()

Scoring History:

,,timestamp,duration,iteration,lambda,predictors,deviance_train,deviance_xval,deviance_se,alpha,iterations,training_rmse,training_logloss,training_r2,training_auc,training_pr_auc,training_lift,training_classification_error
0,,2022-03-21 15:28:01,0.000 sec,2,.38E2,32.0,1.22822,1.255884,0.024855,0.0,NaN,,,,,,,
1,,2022-03-21 15:28:01,0.017 sec,4,.28E2,32.0,1.19859,1.230515,0.023888,0.0,NaN,,,,,,,
2,,2022-03-21 15:28:01,0.031 sec,6,.2E2,32.0,1.161566,1.198369,0.0228,0.0,NaN,,,,,,,
3,,2022-03-21 15:28:01,0.035 sec,8,.15E2,32.0,1.116659,1.158554,0.021614,0.0,NaN,,,,,,,
4,,2022-03-21 15:28:01,0.040 sec,10,.11E2,32.0,1.064056,1.110794,0.020407,0.0,NaN,,,,,,,
5,,2022-03-21 15:28:01,0.047 sec,12,.78E1,32.0,1.004502,1.055518,0.019303,0.0,NaN,,,,,,,
6,,2022-03-21 15:28:01,0.053 sec,14,.57E1,32.0,0.939829,0.993811,0.018376,0.0,NaN,,,,,,,
7,,2022-03-21 15:28:01,0.060 sec,16,.41E1,32.0,0.872005,0.927664,0.017692,0.0,NaN,,,,,,,
8,,2022-03-21 15:28:01,0.067 sec,18,.3E1,32.0,0.803169,0.859203,0.017221,0.0,NaN,,,,,,,
9,,2022-03-21 15:28:01,0.073 sec,20,.22E1,32.0,0.735284,0.790506,0.017043,0.0,NaN,,,,,,,
10,,2022-03-21 15:28:01,0.079 sec,22,.16E1,32.0,0.67001,0.723472,0.017177,0.0,NaN,,,,,,,
11,,2022-03-21 15:28:01,0.085 sec,24,.12E1,32.0,0.608493,0.659621,0.017654,0.0,NaN,,,,,,,
12,,2022-03-21 15:28:01,0.091 sec,26,.85E0,32.0,0.55135,0.599946,0.018463,0.0,NaN,,,,,,,
13,,2022-03-21 15:28:01,0.097 sec,28,.62E0,32.0,0.49884,0.544942,0.019557,0.0,NaN,,,,,,,
14,,2022-03-21 15:28:01,0.103 sec,30,.45E0,32.0,0.450982,0.494757,0.020869,0.0,NaN,,,,,,,
15,,2022-03-21 15:28:01,0.106 sec,32,.33E0,32.0,0.407616,0.449347,0.022329,0.0,NaN,,,,,,,
16,,2022-03-21 15:28:01,0.111 sec,34,.24E0,32.0,0.368477,0.408509,0.023897,0.0,NaN,,,,,,,
17,,2022-03-21 15:28:01,0.117 sec,36,.17E0,32.0,0.333302,0.371978,0.025544,0.0,NaN,,,,,,,
18,,2022-03-21 15:28:01,0.123 sec,38,.13E0,32.0,0.301811,0.339499,0.027266,0.0,NaN,,,,,,,
19,,2022-03-21 15:28:01,0.129 sec,40,.91E-1,32.0,0.27374,0.310815,0.029066,0.0,NaN,,,,,,,

See the whole table with table.as_data_frame()

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0      X.23             0.885117           1.000000    0.065030
1      X.12             0.855501           0.966541    0.062854
2       X.9             0.743094           0.839543    0.054596
3      X.29             0.728577           0.823143    0.053529
4      X.17             0.722781           0.816594    0.053103
5      X.22             0.694434           0.784567    0.051020
6      X.30             0.681010           0.769401    0.050034
7      X.25             0.672402           0.759676    0.049402
8      X.14             0.669744           0.756672    0.049206
9      X.24             0.634891           0.717296    0.046646
10     X.15             0.624027           0.705023    0.045848
11      X.8             0.615714           0.695630    0.045237
12     X.26             0.607888           0.686788    0.044662
13     X.28             0.607143           0.685946    0.044607
14     X.21             0.570119           0.644117    0.041887
15      X.3             0.436593           0.493261    0.032077
16      X.5             0.413871           0.467589    0.030407
17      X.2             0.371550           0.419775    0.027298
18      X.4             0.362004           0.408991    0.026597
19     X.31             0.327350           0.369839    0.024051

See the whole table with table.as_data_frame()

In [13]:
# Get the best model using a non-default metric
#m = aml.get_best_model(criterion="logloss")
#print(m)
best_model = aml.get_best_model()
print(best_model)

Model Details
=============
H2OGeneralizedLinearEstimator :  Generalized Linear Modeling
Model Key:  GLM_1_AutoML_1_20220321_152754


GLM Model: summary

,,family,link,regularization,lambda_search,number_of_predictors_total,number_of_active_predictors,number_of_iterations,training_frame
0,,binomial,logit,Ridge ( lambda = 0.005248 ),"nlambda = 30, lambda.max = 38.202, lambda.min = 0.005248, lambda.1...",31,31,58,AutoML_1_20220321_152754_training_py_5_sid_b915

ModelMetricsBinomialGLM: glm
** Reported on train data. **

MSE: 0.015944831464351737
RMSE: 0.12627284531660693
LogLoss: 0.06540044841416845
Null degrees of freedom: 449
Residual degrees of freedom: 418
Null deviance: 594.6353393993376
Residual deviance: 58.86040357275161
AIC: 122.86040357275161
AUC: 0.9971715636609254
AUCPR: 0.9963210459856495
Gini: 0.9943431273218508

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.41470241461022955:

              B      M   Error          Rate
0      B  280.0    2.0  0.0071   (2.0/282.0)
1      M    4.0  164.0  0.0238   (4.0/168.0)
2  Total  284.0  166.0  0.0133   (6.0/450.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric     threshold       value    idx
0                        max f1  4.147024e-01    0.982036  123.0
1                        max f2  4.147024e-01    0.978520  123.0
2                  max f0point5  5.725890e-01    0.992647  119.0
3                  max accuracy  5.725890e-01    0.986667  119.0
4                 max precision  9.999998e-01    1.000000    0.0
5                    max recall  2.059730e-02    1.000000  206.0
6               max specificity  9.999998e-01    1.000000    0.0
7              max absolute_mcc  5.725890e-01    0.971698  119.0
8    max min_per_class_accuracy  4.147024e-01    0.976190  123.0
9   max mean_per_class_accuracy  4.147024e-01    0.984549  123.0
10                      max tns  9.999998e-01  282.000000    0.0
11                      max fns  9.999998e-01  143.000000    0.0
12                      max fps  7.723554e-08  282.000000  399.0
13                      max tps  2.059730e-02  168.000000  206.0
14                      max tnr  9.999998e-01    1.000000    0.0
15                      max fnr  9.999998e-01    0.851190    0.0
16                      max fpr  7.723554e-08    1.000000  399.0
17                      max tpr  2.059730e-02    1.000000  206.0

Gains/Lift Table: Avg response rate: 37.33 %, avg score: 37.33 %

,group,cumulative_data_fraction,lower_threshold,lift,cumulative_lift,response_rate,score,cumulative_response_rate,cumulative_score,capture_rate,cumulative_capture_rate,gain,cumulative_gain,kolmogorov_smirnov
0,1,0.011111,1.000000e+00,2.678571,2.678571,1.000000,1.000000,1.000000,1.000000,0.029762,0.029762,167.857143,167.857143,0.029762
1,2,0.020000,1.000000e+00,2.678571,2.678571,1.000000,1.000000,1.000000,1.000000,0.023810,0.053571,167.857143,167.857143,0.053571
2,3,0.031111,9.999999e-01,2.678571,2.678571,1.000000,1.000000,1.000000,1.000000,0.029762,0.083333,167.857143,167.857143,0.083333
3,4,0.040000,9.999997e-01,2.678571,2.678571,1.000000,1.000000,1.000000,1.000000,0.023810,0.107143,167.857143,167.857143,0.107143
4,5,0.051111,9.999995e-01,2.678571,2.678571,1.000000,1.000000,1.000000,1.000000,0.029762,0.136905,167.857143,167.857143,0.136905
5,6,0.100000,9.999797e-01,2.678571,2.678571,1.000000,0.999994,1.000000,0.999997,0.130952,0.267857,167.857143,167.857143,0.267857
6,7,0.151111,9.998076e-01,2.678571,2.678571,1.000000,0.999928,1.000000,0.999974,0.136905,0.404762,167.857143,167.857143,0.404762
7,8,0.200000,9.976811e-01,2.678571,2.678571,1.000000,0.999240,1.000000,0.999794,0.130952,0.535714,167.857143,167.857143,0.535714
8,9,0.300000,9.424508e-01,2.678571,2.678571,1.000000,0.984191,1.000000,0.994593,0.267857,0.803571,167.857143,167.857143,0.803571
9,10,0.400000,1.924779e-01,1.785714,2.455357,0.666667,0.615740,0.916667,0.899880,0.178571,0.982143,78.571429,145.535714,0.928951
10,11,0.500000,4.522586e-02,0.119048,1.988095,0.044444,0.099026,0.742222,0.739709,0.011905,0.994048,-88.095238,98.809524,0.788374
11,12,0.600000,1.242193e-02,0.059524,1.666667,0.022222,0.023990,0.622222,0.620422,0.005952,1.000000,-94.047619,66.666667,0.638298
12,13,0.700000,4.203537e-03,0.000000,1.428571,0.000000,0.007475,0.533333,0.532858,0.000000,1.000000,-100.000000,42.857143,0.478723
13,14,0.800000,1.394253e-03,0.000000,1.250000,0.000000,0.002554,0.466667,0.466570,0.000000,1.000000,-100.000000,25.000000,0.319149
14,15,0.900000,2.528208e-04,0.000000,1.111111,0.000000,0.000658,0.414815,0.414802,0.000000,1.000000,-100.000000,11.111111,0.159574
15,16,1.000000,7.723554e-08,0.000000,1.000000,0.000000,0.000111,0.373333,0.373333,0.000000,1.000000,-100.000000,0.000000,0.000000

ModelMetricsBinomialGLM: glm
** Reported on cross-validation data. **

MSE: 0.023707314829084666
RMSE: 0.15397179881096623
LogLoss: 0.09351643208791445
Null degrees of freedom: 449
Residual degrees of freedom: 418
Null deviance: 599.9430074296647
Residual deviance: 84.16478887912304
AIC: 148.16478887912302
AUC: 0.9920634920634921
AUCPR: 0.9913180668482248
Gini: 0.9841269841269842

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.33382471281552806:

              B      M   Error           Rate
0      B  275.0    7.0  0.0248    (7.0/282.0)
1      M    5.0  163.0  0.0298    (5.0/168.0)
2  Total  280.0  170.0  0.0267   (12.0/450.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric     threshold       value    idx
0                        max f1  3.338247e-01    0.964497  135.0
1                        max f2  3.338247e-01    0.967933  135.0
2                  max f0point5  5.875118e-01    0.984848  121.0
3                  max accuracy  5.875118e-01    0.973333  121.0
4                 max precision  9.999999e-01    1.000000    0.0
5                    max recall  1.492819e-03    1.000000  322.0
6               max specificity  9.999999e-01    1.000000    0.0
7              max absolute_mcc  5.875118e-01    0.943753  121.0
8    max min_per_class_accuracy  3.338247e-01    0.970238  135.0
9   max mean_per_class_accuracy  3.338247e-01    0.972708  135.0
10                      max tns  9.999999e-01  282.000000    0.0
11                      max fns  9.999999e-01  152.000000    0.0
12                      max fps  3.708307e-07  282.000000  399.0
13                      max tps  1.492819e-03  168.000000  322.0
14                      max tnr  9.999999e-01    1.000000    0.0
15                      max fnr  9.999999e-01    0.904762    0.0
16                      max fpr  3.708307e-07    1.000000  399.0
17                      max tpr  1.492819e-03    1.000000  322.0

Gains/Lift Table: Avg response rate: 37.33 %, avg score: 37.09 %

,group,cumulative_data_fraction,lower_threshold,lift,cumulative_lift,response_rate,score,cumulative_response_rate,cumulative_score,capture_rate,cumulative_capture_rate,gain,cumulative_gain,kolmogorov_smirnov
0,1,0.013333,1.000000e+00,2.678571,2.678571,1.000000,1.000000,1.000000,1.000000,0.035714,0.035714,167.857143,167.857143,0.035714
1,2,0.020000,1.000000e+00,2.678571,2.678571,1.000000,1.000000,1.000000,1.000000,0.017857,0.053571,167.857143,167.857143,0.053571
2,3,0.031111,9.999998e-01,2.678571,2.678571,1.000000,1.000000,1.000000,1.000000,0.029762,0.083333,167.857143,167.857143,0.083333
3,4,0.040000,9.999992e-01,2.678571,2.678571,1.000000,1.000000,1.000000,1.000000,0.023810,0.107143,167.857143,167.857143,0.107143
4,5,0.051111,9.999988e-01,2.678571,2.678571,1.000000,0.999999,1.000000,1.000000,0.029762,0.136905,167.857143,167.857143,0.136905
5,6,0.100000,9.999736e-01,2.678571,2.678571,1.000000,0.999990,1.000000,0.999995,0.130952,0.267857,167.857143,167.857143,0.267857
6,7,0.151111,9.996960e-01,2.678571,2.678571,1.000000,0.999887,1.000000,0.999958,0.136905,0.404762,167.857143,167.857143,0.404762
7,8,0.200000,9.967022e-01,2.678571,2.678571,1.000000,0.998872,1.000000,0.999693,0.130952,0.535714,167.857143,167.857143,0.535714
8,9,0.300000,9.307274e-01,2.678571,2.678571,1.000000,0.978239,1.000000,0.992542,0.267857,0.803571,167.857143,167.857143,0.803571
9,10,0.400000,2.204994e-01,1.666667,2.425595,0.622222,0.583056,0.905556,0.890170,0.166667,0.970238,66.666667,142.559524,0.909954
10,11,0.500000,5.282988e-02,0.178571,1.976190,0.066667,0.108407,0.737778,0.733818,0.017857,0.988095,-82.142857,97.619048,0.778875
11,12,0.600000,1.520830e-02,0.059524,1.656746,0.022222,0.027144,0.618519,0.616039,0.005952,0.994048,-94.047619,65.674603,0.628799
12,13,0.700000,4.747271e-03,0.000000,1.420068,0.000000,0.008316,0.530159,0.529221,0.000000,0.994048,-100.000000,42.006803,0.469225
13,14,0.800000,1.483150e-03,0.059524,1.250000,0.022222,0.003056,0.466667,0.463451,0.005952,1.000000,-94.047619,25.000000,0.319149
14,15,0.900000,3.548980e-04,0.000000,1.111111,0.000000,0.000762,0.414815,0.412041,0.000000,1.000000,-100.000000,11.111111,0.159574
15,16,1.000000,3.700000e-07,0.000000,1.000000,0.000000,0.000134,0.373333,0.370850,0.000000,1.000000,-100.000000,0.000000,0.000000

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,accuracy,0.977778,0.017568,1.000000,0.977778,0.966667,0.955556,0.988889
1,auc,0.991709,0.011953,1.000000,0.997942,0.995445,0.970679,0.994479
2,err,0.022222,0.017568,0.000000,0.022222,0.033333,0.044444,0.011111
3,err_count,2.000000,1.581139,0.000000,2.000000,3.000000,4.000000,1.000000
4,f0point5,0.978179,0.017056,1.000000,0.957447,0.967742,0.975610,0.990099
5,f1,0.969952,0.021628,1.000000,0.972973,0.960000,0.941176,0.975610
6,f2,0.962404,0.035584,1.000000,0.989011,0.952381,0.909091,0.961538
7,lift_top_group,2.817314,0.822681,2.432432,2.500000,2.368421,2.500000,4.285714
8,logloss,0.089257,0.056666,0.033640,0.077761,0.089971,0.183341,0.061572
9,max_per_class_error,0.049680,0.040046,0.000000,0.037037,0.052632,0.111111,0.047619
10,mcc,0.953087,0.034621,1.000000,0.955134,0.931681,0.909718,0.968904
11,mean_per_class_accuracy,0.973237,0.020652,1.000000,0.981482,0.964069,0.944444,0.976190
12,mean_per_class_error,0.026763,0.020652,0.000000,0.018519,0.035931,0.055556,0.023810
13,mse,0.023628,0.015040,0.005620,0.022521,0.027841,0.046089,0.016071
14,null_deviance,119.988600,5.650968,122.759590,121.567660,124.005860,121.567660,110.042240
15,pr_auc,0.989826,0.011474,1.000000,0.996996,0.994184,0.971319,0.986632
16,precision,0.984068,0.023619,1.000000,0.947368,0.972973,1.000000,1.000000
17,r2,0.897389,0.060567,0.976785,0.906164,0.885873,0.807964,0.910160
18,recall,0.957728,0.045958,1.000000,1.000000,0.947368,0.888889,0.952381
19,residual_deviance,16.066265,10.199904,6.055276,13.997009,16.194714,33.001434,11.082891

See the whole table with table.as_data_frame()

Scoring History:

,,timestamp,duration,iteration,lambda,predictors,deviance_train,deviance_xval,deviance_se,alpha,iterations,training_rmse,training_logloss,training_r2,training_auc,training_pr_auc,training_lift,training_classification_error
0,,2022-03-21 15:28:01,0.000 sec,2,.38E2,32.0,1.22822,1.255884,0.024855,0.0,NaN,,,,,,,
1,,2022-03-21 15:28:01,0.017 sec,4,.28E2,32.0,1.19859,1.230515,0.023888,0.0,NaN,,,,,,,
2,,2022-03-21 15:28:01,0.031 sec,6,.2E2,32.0,1.161566,1.198369,0.0228,0.0,NaN,,,,,,,
3,,2022-03-21 15:28:01,0.035 sec,8,.15E2,32.0,1.116659,1.158554,0.021614,0.0,NaN,,,,,,,
4,,2022-03-21 15:28:01,0.040 sec,10,.11E2,32.0,1.064056,1.110794,0.020407,0.0,NaN,,,,,,,
5,,2022-03-21 15:28:01,0.047 sec,12,.78E1,32.0,1.004502,1.055518,0.019303,0.0,NaN,,,,,,,
6,,2022-03-21 15:28:01,0.053 sec,14,.57E1,32.0,0.939829,0.993811,0.018376,0.0,NaN,,,,,,,
7,,2022-03-21 15:28:01,0.060 sec,16,.41E1,32.0,0.872005,0.927664,0.017692,0.0,NaN,,,,,,,
8,,2022-03-21 15:28:01,0.067 sec,18,.3E1,32.0,0.803169,0.859203,0.017221,0.0,NaN,,,,,,,
9,,2022-03-21 15:28:01,0.073 sec,20,.22E1,32.0,0.735284,0.790506,0.017043,0.0,NaN,,,,,,,
10,,2022-03-21 15:28:01,0.079 sec,22,.16E1,32.0,0.67001,0.723472,0.017177,0.0,NaN,,,,,,,
11,,2022-03-21 15:28:01,0.085 sec,24,.12E1,32.0,0.608493,0.659621,0.017654,0.0,NaN,,,,,,,
12,,2022-03-21 15:28:01,0.091 sec,26,.85E0,32.0,0.55135,0.599946,0.018463,0.0,NaN,,,,,,,
13,,2022-03-21 15:28:01,0.097 sec,28,.62E0,32.0,0.49884,0.544942,0.019557,0.0,NaN,,,,,,,
14,,2022-03-21 15:28:01,0.103 sec,30,.45E0,32.0,0.450982,0.494757,0.020869,0.0,NaN,,,,,,,
15,,2022-03-21 15:28:01,0.106 sec,32,.33E0,32.0,0.407616,0.449347,0.022329,0.0,NaN,,,,,,,
16,,2022-03-21 15:28:01,0.111 sec,34,.24E0,32.0,0.368477,0.408509,0.023897,0.0,NaN,,,,,,,
17,,2022-03-21 15:28:01,0.117 sec,36,.17E0,32.0,0.333302,0.371978,0.025544,0.0,NaN,,,,,,,
18,,2022-03-21 15:28:01,0.123 sec,38,.13E0,32.0,0.301811,0.339499,0.027266,0.0,NaN,,,,,,,
19,,2022-03-21 15:28:01,0.129 sec,40,.91E-1,32.0,0.27374,0.310815,0.029066,0.0,NaN,,,,,,,

See the whole table with table.as_data_frame()

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0      X.23             0.885117           1.000000    0.065030
1      X.12             0.855501           0.966541    0.062854
2       X.9             0.743094           0.839543    0.054596
3      X.29             0.728577           0.823143    0.053529
4      X.17             0.722781           0.816594    0.053103
5      X.22             0.694434           0.784567    0.051020
6      X.30             0.681010           0.769401    0.050034
7      X.25             0.672402           0.759676    0.049402
8      X.14             0.669744           0.756672    0.049206
9      X.24             0.634891           0.717296    0.046646
10     X.15             0.624027           0.705023    0.045848
11      X.8             0.615714           0.695630    0.045237
12     X.26             0.607888           0.686788    0.044662
13     X.28             0.607143           0.685946    0.044607
14     X.21             0.570119           0.644117    0.041887
15      X.3             0.436593           0.493261    0.032077
16      X.5             0.413871           0.467589    0.030407
17      X.2             0.371550           0.419775    0.027298
18      X.4             0.362004           0.408991    0.026597
19     X.31             0.327350           0.369839    0.024051

See the whole table with table.as_data_frame()

In [14]:
best_model.model_performance(test)

ModelMetricsBinomialGLM: glm
** Reported on test data. **

MSE: 0.019369176644234452
RMSE: 0.13917318938730425
LogLoss: 0.0774088079780402
Null degrees of freedom: 118
Residual degrees of freedom: 87
Null deviance: 156.80603386971518
Residual deviance: 18.423296298773565
AIC: 82.42329629877356
AUC: 0.9951515151515152
AUCPR: 0.993888320612225
Gini: 0.9903030303030305

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.5156484474178668:

             B     M   Error          Rate
0      B  75.0   0.0     0.0    (0.0/75.0)
1      M   1.0  43.0  0.0227    (1.0/44.0)
2  Total  76.0  43.0  0.0084   (1.0/119.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric  threshold      value    idx
0                        max f1   0.515648   0.988506   39.0
1                        max f2   0.515648   0.981735   39.0
2                  max f0point5   0.515648   0.995370   39.0
3                  max accuracy   0.515648   0.991597   39.0
4                 max precision   1.000000   1.000000    0.0
5                    max recall   0.061115   1.000000   56.0
6               max specificity   1.000000   1.000000    0.0
7              max absolute_mcc   0.515648   0.982046   39.0
8    max min_per_class_accuracy   0.515648   0.977273   39.0
9   max mean_per_class_accuracy   0.515648   0.988636   39.0
10                      max tns   1.000000  75.000000    0.0
11                      max fns   1.000000  40.000000    0.0
12                      max fps   0.000049  75.000000  115.0
13                      max tps   0.061115  44.000000   56.0
14                      max tnr   1.000000   1.000000    0.0
15                      max fnr   1.000000   0.909091    0.0
16                      max fpr   0.000049   1.000000  115.0
17                      max tpr   0.061115   1.000000   56.0

Gains/Lift Table: Avg response rate: 36.97 %, avg score: 37.42 %

,group,cumulative_data_fraction,lower_threshold,lift,cumulative_lift,response_rate,score,cumulative_response_rate,cumulative_score,capture_rate,cumulative_capture_rate,gain,cumulative_gain,kolmogorov_smirnov
0,1,0.016807,1.000000,2.704545,2.704545,1.000000,1.000000,1.000000,1.000000,0.045455,0.045455,170.454545,170.454545,0.045455
1,2,0.025210,1.000000,2.704545,2.704545,1.000000,1.000000,1.000000,1.000000,0.022727,0.068182,170.454545,170.454545,0.068182
2,3,0.033613,1.000000,2.704545,2.704545,1.000000,1.000000,1.000000,1.000000,0.022727,0.090909,170.454545,170.454545,0.090909
3,4,0.042017,1.000000,2.704545,2.704545,1.000000,1.000000,1.000000,1.000000,0.022727,0.113636,170.454545,170.454545,0.113636
4,5,0.050420,1.000000,2.704545,2.704545,1.000000,1.000000,1.000000,1.000000,0.022727,0.136364,170.454545,170.454545,0.136364
5,6,0.100840,0.999970,2.704545,2.704545,1.000000,0.999988,1.000000,0.999994,0.136364,0.272727,170.454545,170.454545,0.272727
6,7,0.151261,0.999636,2.704545,2.704545,1.000000,0.999877,1.000000,0.999955,0.136364,0.409091,170.454545,170.454545,0.409091
7,8,0.201681,0.998289,2.704545,2.704545,1.000000,0.999126,1.000000,0.999748,0.136364,0.545455,170.454545,170.454545,0.545455
8,9,0.302521,0.929999,2.704545,2.704545,1.000000,0.985335,1.000000,0.994944,0.272727,0.818182,170.454545,170.454545,0.818182
9,10,0.403361,0.172399,1.577652,2.422822,0.583333,0.573607,0.895833,0.889609,0.159091,0.977273,57.765152,142.282197,0.910606
10,11,0.504202,0.061115,0.225379,1.983333,0.083333,0.104408,0.733333,0.732569,0.022727,1.000000,-77.462121,98.333333,0.786667
11,12,0.596639,0.022354,0.000000,1.676056,0.000000,0.034382,0.619718,0.624399,0.000000,1.000000,-100.000000,67.605634,0.640000
12,13,0.697479,0.004736,0.000000,1.433735,0.000000,0.012197,0.530120,0.535888,0.000000,1.000000,-100.000000,43.373494,0.480000
13,14,0.798319,0.001676,0.000000,1.252632,0.000000,0.002824,0.463158,0.468554,0.000000,1.000000,-100.000000,25.263158,0.320000
14,15,0.899160,0.000471,0.000000,1.112150,0.000000,0.000797,0.411215,0.416095,0.000000,1.000000,-100.000000,11.214953,0.160000
15,16,1.000000,0.000049,0.000000,1.000000,0.000000,0.000221,0.369748,0.374158,0.000000,1.000000,-100.000000,0.000000,0.000000

In [20]:
best_model.accuracy()

[[0.5725890298840417, 0.9866666666666667]]